# URLs de otros servicios
usuarios.service.url=http://localhost:8081
reservas.service.url=http://localhost:8082

# Base de datos
spring.datasource.url=jdbc:mariadb://localhost:3306/usuarios_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Servidor
server.port=8081

# JPA y Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.application.name=usuarios

# Seguridad simple para desarrollo
app.security.admin.username=admin
app.security.admin.password=admin123
app.security.user.username=usuario
app.security.user.password=usuario123

#Testing
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.htm
