server.port=8083
spring.application.name=administracion-usuarios

# URL del servicio de usuarios (al que consumir� v�a Feign)
usuarios.service.url=http://localhost:8081

# Base de datos propia (para auditor�a, logs, etc.)
spring.datasource.url=jdbc:mariadb://localhost:3306/admin_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA y Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration